### ISSUE TITLE
Can't create .exe with pyinstaller when using pygame_menu

### ISSUE THREAD

**Issue by AlcuZan** [ppizarror/pygame-menu#264]
**Environment information**
Describe your environment information, such as:
- SO: win10
- python version: v3.9
- pygame version: v2.0.1
- pygame-menu version: v3.5.1

**Describe the bug**
![grafik](https://user-images.githubusercontent.com/19841508/104810690-acf15300-57f6-11eb-874e-33448fd5bb5d.png)

**To Reproduce**
With `pyinstaller` installed via pip, just take any of the examples (for example `simple.py`), run `pyinstaller -F simple.py`, then try to execute simple.exe in the `dist` folder.

**Expected behavior**
When executing the .exe, the program should run. Instead it crashes.

**Comment by ppizarror** [comment]
Fixed, Added ``pygame_menu/__pyinstaller``. It works as intended. I'll push the changes to v4 and v3 as well.

![image](https://user-images.githubusercontent.com/12925256/104817436-0b6eff00-5800-11eb-9898-5f1ae28dbab9.png)

**Comment by ppizarror** [comment]
Works for both ``pyinstaller -D`` and ``pyinstaller -F``. I had no idea this module existed, in the past I used py2exe but that didn't work well.

**Comment by ppizarror** [comment]
New version published =)

**Comment by AlcuZan** [comment]
Hey Pablo,

I downloaded the latest v3 but still can't make PyInstaller work:
[cid:image001.png@01D6ECC3.DCB510C0]

What am I missing here?

Greetings
Manu

Von: Pablo Pizarro R. <notifications@github.com>
Gesendet: Sonntag, 17. Januar 2021 05:31
An: ppizarror/pygame-menu <pygame-menu@noreply.github.com>
Cc: AlcuZan <manuel_baudach@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [ppizarror/pygame-menu] Can't create .exe with pyinstaller when using pygame_menu (#264)


New version published =)

-

**Comment by ppizarror** [comment]
Did you install it with pip? I forgot to update the version ahah.

I uninstalled my version, did “py -3.7 -m pip install pygame-menu==3.5.2” and it worked.

If there’s any error, please create a new issue. I could not see your attached image

 

──

Pablo

 

 

 

 

De: AlcuZan <notifications@github.com> 
Enviado el: domingo, 17 de enero de 2021 07:29
Para: ppizarror/pygame-menu <pygame-menu@noreply.github.com>
CC: Pablo Pizarro R. <pablo.pizarro@ing.uchile.cl>; State change <state_change@noreply.github.com>
Asunto: Re: [ppizarror/pygame-menu] Can't create .exe with pyinstaller when using pygame_menu (#264)

 

Hey Pablo,

I downloaded the latest v3 but still can't make PyInstaller work:
[cid:image001.png@01D6ECC3.DCB510C0]

What am I missing here?

Greetings
Manu

Von: Pablo Pizarro R. <notifications@github.com <mailto:notifications@github.com> >
Gesendet: Sonntag, 17. Januar 2021 05:31
An: ppizarror/pygame-menu <pygame-menu@noreply.github.com <mailto:pygame-menu@noreply.github.com> >
Cc: AlcuZan <manuel_baudach@hotmail.com <mailto:manuel_baudach@hotmail.com> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Betreff: Re: [ppizarror/pygame-menu] Can't create .exe with pyinstaller when using pygame_menu (#264)


New version published =)

-
